/**
 * mockData — seed inventory for the Oran showroom pitch prototype.
 *
 * Swap out these entries in under 5 minutes with the dealership's real
 * stock before a client meeting. Keep the count between 3 and 8 — the
 * FeaturedVehicles grid is optimized for that range.
 */
import type { Vehicle } from "./vehicles";

const img = (id: string) => `https://images.unsplash.com/${id}?auto=format&fit=crop&w=1600&q=80`;

export const featuredVehicles: Vehicle[] = [
  {
    id: "v-001",
    slug: "mercedes-c300-2023",
    brand: "Mercedes-Benz",
    model: "Classe C 300",
    year: 2023,
    priceDzd: 12_900_000,
    mileageKm: 18_500,
    fuel: "essence",
    transmission: "automatique",
    condition: "occasion",
    bodyStyle: "Berline",
    color: "Noir Obsidienne",
    engineDisplacement: "2.0 L Turbo",
    tagline: "Pack AMG Line, intérieur cuir Nappa, ambiance 64 couleurs.",
    description:
      'Berline premium entretenue exclusivement chez concessionnaire, carnet à jour, second propriétaire. Finition AMG Line intérieure et extérieure, jantes 19", système MBUX avec double écran incurvé. Véhicule non fumeur, disponible pour essai sur rendez-vous.',
    images: [
      img("photo-1618843479313-40f8afb4b4d8"),
      img("photo-1552519507-da3b142c6e3d"),
      img("photo-1553440569-bcc63803a83d"),
      img("photo-1580273916550-e323be2ae537"),
    ],
    highlights: ["Pack AMG", "Toit ouvrant", "Caméra 360°"],
    equipment: [
      "Toit ouvrant panoramique",
      "Sièges cuir Nappa chauffants",
      "Caméra 360° + assistance parking",
      "Éclairage d'ambiance 64 couleurs",
      "MBUX avec commande vocale",
      'Jantes AMG 19"',
      "Apple CarPlay / Android Auto",
      "Régulateur adaptatif Distronic",
    ],
    specs: [
      { label: "Puissance", value: "258 ch" },
      { label: "Couple", value: "400 Nm" },
      { label: "0–100 km/h", value: "6.0 s" },
      { label: "Vitesse max", value: "250 km/h" },
      { label: "Consommation", value: "7.2 L/100" },
      { label: "Traction", value: "Propulsion" },
    ],
  },
  {
    id: "v-002",
    slug: "bmw-x5-xdrive40i-2024",
    brand: "BMW",
    model: "X5 xDrive40i",
    year: 2024,
    priceDzd: 21_500_000,
    mileageKm: 6_200,
    fuel: "essence",
    transmission: "automatique",
    condition: "neuf",
    bodyStyle: "SUV",
    color: "Blanc Alpin",
    engineDisplacement: "3.0 L 6-cyl",
    tagline: "M Sport Package, sièges chauffants, Harman Kardon.",
    description:
      'SUV premium neuf, disponible immédiatement. Pack M Sport intégral, jantes M 21", freins M Sport. Livré avec garantie constructeur 2 ans + extension possible. Financement sur mesure disponible.',
    images: [
      img("photo-1555215695-3004980ad54e"),
      img("photo-1544636331-e26879cd4d9b"),
      img("photo-1616422285623-13ff0162193c"),
      img("photo-1622199678292-c95d90929b4d"),
    ],
    highlights: ["M Sport", "Cuir Merino", "Head-up display"],
    equipment: [
      "Pack M Sport intégral",
      'Jantes M 21"',
      "Sièges Merino ventilés",
      "Harman Kardon Surround",
      "Head-up display couleur",
      "Toit ouvrant panoramique Sky Lounge",
      "Attelage électrique",
      "Assistant conduite Professional",
    ],
    specs: [
      { label: "Puissance", value: "381 ch" },
      { label: "Couple", value: "540 Nm" },
      { label: "0–100 km/h", value: "5.4 s" },
      { label: "Vitesse max", value: "250 km/h" },
      { label: "Consommation", value: "9.1 L/100" },
      { label: "Traction", value: "xDrive 4×4" },
    ],
  },
  {
    id: "v-003",
    slug: "audi-q7-55-tfsi-2023",
    brand: "Audi",
    model: "Q7 55 TFSI",
    year: 2023,
    priceDzd: 19_800_000,
    mileageKm: 24_000,
    fuel: "essence",
    transmission: "automatique",
    condition: "occasion",
    bodyStyle: "SUV 7 places",
    color: "Gris Daytona",
    engineDisplacement: "3.0 L V6",
    tagline: "S line, 7 places, suspension pneumatique adaptative.",
    description:
      "SUV familial haut de gamme, 7 places modulables, entretenu chez Audi. Suspension pneumatique adaptative, Matrix LED, virtual cockpit. Idéal pour famille exigeante — véhicule réservé, contactez-nous pour la liste d'attente.",
    images: [
      img("photo-1606664515524-ed2f786a0bd6"),
      img("photo-1614026480209-cb75c2a8c8e5"),
      img("photo-1606611013016-969c19ba27bb"),
      img("photo-1610647752706-3bb12232b3ab"),
    ],
    highlights: ["7 places", "S line", "Matrix LED"],
    equipment: [
      "7 places réelles",
      "Suspension pneumatique adaptative",
      "Phares Matrix LED HD",
      'Virtual Cockpit 12.3"',
      "Bang & Olufsen 3D",
      "Sièges S line ventilés",
      "Ouverture coffre mains libres",
      "Pack éclairage d'ambiance",
    ],
    specs: [
      { label: "Puissance", value: "340 ch" },
      { label: "Couple", value: "500 Nm" },
      { label: "0–100 km/h", value: "5.9 s" },
      { label: "Vitesse max", value: "250 km/h" },
      { label: "Consommation", value: "9.6 L/100" },
      { label: "Traction", value: "Quattro" },
    ],
    reserved: true,
  },
  {
    id: "v-004",
    slug: "range-rover-sport-2024",
    brand: "Land Rover",
    model: "Range Rover Sport",
    year: 2024,
    priceDzd: 28_400_000,
    mileageKm: 3_100,
    fuel: "diesel",
    transmission: "automatique",
    condition: "neuf",
    bodyStyle: "SUV",
    color: "Noir Santorin",
    engineDisplacement: "3.0 L D350",
    tagline: "Dynamic HSE, finition Windsor, système Meridian.",
    description:
      "Icône du luxe britannique, à peine rodée. Finition Dynamic HSE, cuir Windsor semi-aniline, système Meridian Signature 3D 29 haut-parleurs. Pack tout-terrain complet. Disponible immédiatement.",
    images: [
      img("photo-1600661653561-629509216228"),
      img("photo-1519834785169-98be25ec3f84"),
      img("photo-1631295868223-63265b40d9e4"),
      img("photo-1601362840469-51e4d8d58785"),
    ],
    highlights: ["Dynamic HSE", "Meridian 3D", "Vision nocturne"],
    equipment: [
      "Finition Dynamic HSE",
      "Cuir Windsor semi-aniline",
      "Meridian Signature Sound 3D",
      "Vision nocturne",
      "Suspension pneumatique électronique",
      "Terrain Response 2 automatique",
      "Toit ouvrant panoramique fixe",
      "Pack Off-Road",
    ],
    specs: [
      { label: "Puissance", value: "350 ch" },
      { label: "Couple", value: "700 Nm" },
      { label: "0–100 km/h", value: "6.6 s" },
      { label: "Vitesse max", value: "234 km/h" },
      { label: "Consommation", value: "8.4 L/100" },
      { label: "Traction", value: "4×4 permanent" },
    ],
  },
  {
    id: "v-005",
    slug: "porsche-macan-s-2023",
    brand: "Porsche",
    model: "Macan S",
    year: 2023,
    priceDzd: 24_900_000,
    mileageKm: 12_800,
    fuel: "essence",
    transmission: "automatique",
    condition: "occasion",
    bodyStyle: "SUV Coupé",
    color: "Bleu Nuit Métallisé",
    engineDisplacement: "2.9 L V6 biturbo",
    tagline: "Pack Sport Chrono, PASM, échappement sport.",
    description:
      "Le SUV Porsche par excellence — comportement de sportive, praticité au quotidien. Pack Sport Chrono avec Launch Control, PASM, échappement sport à commande. Entretien Porsche à jour, carnet complet.",
    images: [
      img("photo-1503376780353-7e6692767b70"),
      img("photo-1544829099-b9a0c07fad1a"),
      img("photo-1580414057403-c5f451f30e1c"),
      img("photo-1568844293986-8d0400bd4745"),
    ],
    highlights: ["Sport Chrono", "PASM", "Bose"],
    equipment: [
      "Pack Sport Chrono",
      "PASM — suspension adaptative",
      "Échappement sport à commande",
      "Système Bose Surround",
      "Sièges sport adaptatifs 18 réglages",
      "Volant sport GT chauffant",
      'Jantes RS Spyder Design 21"',
      "Aide au stationnement Surround View",
    ],
    specs: [
      { label: "Puissance", value: "380 ch" },
      { label: "Couple", value: "520 Nm" },
      { label: "0–100 km/h", value: "4.6 s" },
      { label: "Vitesse max", value: "259 km/h" },
      { label: "Consommation", value: "9.8 L/100" },
      { label: "Traction", value: "PTM 4×4" },
    ],
  },
  {
    id: "v-006",
    slug: "tesla-model-y-lr-2024",
    brand: "Tesla",
    model: "Model Y Long Range",
    year: 2024,
    priceDzd: null,
    mileageKm: 0,
    fuel: "electrique",
    transmission: "automatique",
    condition: "neuf",
    bodyStyle: "SUV Électrique",
    color: "Blanc Nacré Multicouche",
    engineDisplacement: "Dual Motor AWD",
    tagline: "Autonomie 533 km, transmission intégrale, Autopilot.",
    description:
      "Le SUV électrique le plus vendu au monde. Autonomie WLTP 533 km, 0-100 en 5 s, Autopilot avancé. Superchargeurs Tesla accessibles à Alger. Livraison sur commande, prix communiqué sur demande selon la configuration.",
    images: [
      img("photo-1617788138017-80ad40651399"),
      img("photo-1560958089-b8a1929cea89"),
      img("photo-1553260168-69b041873e65"),
      img("photo-1571127236794-81c8bbfe0a0e"),
    ],
    highlights: ["Autopilot", "AWD", "Toit panoramique"],
    equipment: [
      "Autopilot avancé",
      'Écran central 15" tactile',
      "Toit panoramique vitré fixe",
      "Sièges avant chauffants + ventilés",
      "Système audio premium 14 HP",
      "Recharge Supercharger V3",
      "Mise à jour OTA à vie",
      "Coffre avant + arrière",
    ],
    specs: [
      { label: "Puissance", value: "384 ch" },
      { label: "Couple", value: "510 Nm" },
      { label: "0–100 km/h", value: "5.0 s" },
      { label: "Autonomie WLTP", value: "533 km" },
      { label: "Recharge 10-80%", value: "27 min" },
      { label: "Traction", value: "Dual Motor AWD" },
    ],
  },
];
