/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminNewRouteImport } from './routes/admin/new'
import { Route as AdminEditSlugRouteImport } from './routes/admin/edit.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNewRoute = AdminNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEditSlugRoute = AdminEditSlugRouteImport.update({
  id: '/edit/$slug',
  path: '/edit/$slug',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/new': typeof AdminNewRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/edit/$slug': typeof AdminEditSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/new': typeof AdminNewRoute
  '/admin': typeof AdminIndexRoute
  '/admin/edit/$slug': typeof AdminEditSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/new': typeof AdminNewRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/edit/$slug': typeof AdminEditSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/login'
    | '/admin/new'
    | '/admin/'
    | '/admin/edit/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin/login' | '/admin/new' | '/admin' | '/admin/edit/$slug'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin/login'
    | '/admin/new'
    | '/admin/'
    | '/admin/edit/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/new': {
      id: '/admin/new'
      path: '/new'
      fullPath: '/admin/new'
      preLoaderRoute: typeof AdminNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/edit/$slug': {
      id: '/admin/edit/$slug'
      path: '/edit/$slug'
      fullPath: '/admin/edit/$slug'
      preLoaderRoute: typeof AdminEditSlugRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminLoginRoute: typeof AdminLoginRoute
  AdminNewRoute: typeof AdminNewRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminEditSlugRoute: typeof AdminEditSlugRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminLoginRoute: AdminLoginRoute,
  AdminNewRoute: AdminNewRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminEditSlugRoute: AdminEditSlugRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
